FROM ubuntu:22.04 AS base

ENV LD_LIBRARY_PATH=/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/driver/lib64/common:$LD_LIBRARY_PATH
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai

# Configure the Ubuntu mirror. An example is provided below:
RUN echo "deb http://mirrors.tools.huawei.com/ubuntu-ports/ jammy main restricted universe multiverse" > /etc/apt/sources.list && \
    echo "deb-src http://mirrors.tools.huawei.com/ubuntu-ports/ jammy main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb http://mirrors.tools.huawei.com/ubuntu-ports/ jammy-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb-src http://repo.huaweicloud.com/ubuntu-ports/ jammy-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb http://repo.huaweicloud.com/ubuntu-ports/ jammy-backports main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb-src http://repo.huaweicloud.com/ubuntu-ports/ jammy-backports main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb http://ports.ubuntu.com/ubuntu-ports/ jammy-security main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb-src http://ports.ubuntu.com/ubuntu-ports/ jammy-security main restricted universe multiverse" >> /etc/apt/sources.list

RUN apt-get update && \
    apt-get upgrade -y

# Python Environment Variables
ARG PYTHON_VERSION
ARG PYTHON_MD5
ARG PYTHON_MAJOR_VERSION
ARG PYTHON_SHORT_VERSION

ENV PYTHON_VERSION=$PYTHON_VERSION \
    PYTHON_MAJOR_VERSION=$PYTHON_MAJOR_VERSION \
    PYTHON_SHORT_VERSION=$PYTHON_SHORT_VERSION


#######################################################################################
# The codes below follow the example of the official python image
# https://github.com/docker-library/python/blob/master/3.11/slim-bookworm/Dockerfile
#######################################################################################

# ensure local python is preferred over distribution python
ENV PATH /usr/local/bin:$PATH

# cannot remove LANG even though https://bugs.python.org/issue19846 is fixed
# last attempted removal of LANG broke many users:
# https://github.com/docker-library/python/pull/570
ENV LANG C.UTF-8

# Runtime Dependencies
RUN set -eux; \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        netbase \
        tzdata \
        wget \
        vim \
    ; \
    rm -rf /var/lib/apt/lists/*

# Install Python Build Dependencies
RUN set -eux; \
    savedAptMark="$(apt-mark showmanual)"; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        dpkg-dev \
        gcc \
        gnupg \
        libbluetooth-dev \
        libbz2-dev \
        libc6-dev \
        libdb-dev \
        libffi-dev \
        libgdbm-dev \
        liblzma-dev \
        libncursesw5-dev \
        libreadline-dev \
        libsqlite3-dev \
        libssl-dev \
        make \
        tk-dev \
        uuid-dev \
        xz-utils \
        zlib1g-dev \
    ; \
    # Download and Verify Python Source
    wget -O python.tar.xz --no-check-certificate \
        "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz"; \
    echo "$PYTHON_MD5 *python.tar.xz" | md5sum -c -; \
    mkdir -p /usr/src/python; \
    tar --extract --directory /usr/src/python --strip-components=1 --file python.tar.xz; \
    rm python.tar.xz; \
    \
    # Configure and Build Python
    cd /usr/src/python; \
    gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"; \
    ./configure \
        --build="$gnuArch" \
        --enable-loadable-sqlite-extensions \
        --enable-optimizations \
        --enable-option-checking=fatal \
        --enable-shared \
        --with-lto \
        --with-ensurepip \
    ; \
    EXTRA_CFLAGS="$(dpkg-buildflags --get CFLAGS)"; \
    LDFLAGS="$(dpkg-buildflags --get LDFLAGS)"; \
    LDFLAGS="${LDFLAGS:--Wl},--strip-all"; \
    make -j 64 \
        "EXTRA_CFLAGS=${EXTRA_CFLAGS:-}" \
        "LDFLAGS=${LDFLAGS:-}" \
    ; \
    # Prevent accidental usage of system-installed libpython
    rm python; \
    make -j 64 \
        "EXTRA_CFLAGS=${EXTRA_CFLAGS:-}" \
        "LDFLAGS=${LDFLAGS:--Wl},-rpath='\$\$ORIGIN/../lib'" \
        python \
    ; \
    make install; \
    \
    # Cleanup Python Source and Unnecessary Files
    cd /; \
    rm -rf /usr/src/python; \
    \
    find /usr/local -depth \
        \( \
            \( -type d -a \( -name test -o -name tests -o -name idle_test \) \) \
            -o \( -type f -a \( -name '*.pyc' -o -name '*.pyo' -o -name 'libpython*.a' \) \) \
        \) -exec rm -rf '{}' + \
    ; \
    \
    ldconfig; \
    \
    # Clean up apt packages
    apt-mark auto '.*' > /dev/null; \
    apt-mark manual $savedAptMark; \
    find /usr/local -type f -executable -not \( -name '*tkinter*' \) -exec ldd '{}' ';' \
        | awk '/=>/ { so = $(NF-1); if (index(so, "/usr/local/") == 1) { next }; gsub("^/(usr/)?", "", so); printf "*%s\n", so }' \
        | sort -u \
        | xargs -r dpkg-query --search \
        | cut -d: -f1 \
        | sort -u \
        | xargs -r apt-mark manual \
    ; \
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
    rm -rf /var/lib/apt/lists/*; \
    \
    # Install pip and setuptools
    export PYTHONDONTWRITEBYTECODE=1; \
    python3 --version; \
    \
    pip3 install \
        --disable-pip-version-check \
        --no-cache-dir \
        --no-compile \
        'setuptools==65.5.1' \
        wheel \
    ; \
    pip3 --version

# Create Symlinks for Python Executables
RUN set -eux; \
    for src in idle3 pip3 pydoc3 python3 python3-config; do \
        dst="$(echo "$src" | tr -d 3)"; \
        [ -s "/usr/local/bin/$src" ]; \
        [ ! -e "/usr/local/bin/$dst" ]; \
        ln -svT "$src" "/usr/local/bin/$dst"; \
    done

# Create User and Set Working Directory
RUN groupadd -g 1000 mindie && \
    useradd -u 1000 -g 1000 -m mindieuser

WORKDIR /home/mindieuser
USER mindieuser

################################################## Install CANN ##################################################
FROM base AS cann

ARG DEVICE
ARG CANN_VERSION
ARG ARCH

# Toolkit envs
ENV ASCEND_TOOLKIT_HOME=/home/mindieuser/Ascend/ascend-toolkit/latest
ENV LD_LIBRARY_PATH=${ASCEND_TOOLKIT_HOME}/lib64:${ASCEND_TOOLKIT_HOME}/lib64/plugin/opskernel:$LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=${ASCEND_TOOLKIT_HOME}/lib64/plugin/nnengine:${ASCEND_TOOLKIT_HOME}/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/${ARCH}:$LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=${ASCEND_TOOLKIT_HOME}/tools/aml/lib64:${ASCEND_TOOLKIT_HOME}/tools/aml/lib64/plugin:$LD_LIBRARY_PATH
ENV PYTHONPATH=${ASCEND_TOOLKIT_HOME}/python/site-packages:${ASCEND_TOOLKIT_HOME}/opp/built-in/op_impl/ai_core/tbe:$PYTHONPATH
ENV PATH=${ASCEND_TOOLKIT_HOME}/bin:${ASCEND_TOOLKIT_HOME}/compiler/ccec_compiler/bin:${ASCEND_TOOLKIT_HOME}/tools/ccec_compiler/bin:$PATH
ENV ASCEND_AICPU_PATH=${ASCEND_TOOLKIT_HOME} \
    ASCEND_OPP_PATH=${ASCEND_TOOLKIT_HOME}/opp \
    TOOLCHAIN_HOME=${ASCEND_TOOLKIT_HOME}/toolkit \
    ASCEND_HOME_PATH=${ASCEND_TOOLKIT_HOME}

# NNAL envs
ENV ATB_HOME_PATH=/home/mindieuser/Ascend/nnal/atb/latest/atb/cxx_abi_0
ENV LD_LIBRARY_PATH=${ATB_HOME_PATH}/lib:${ATB_HOME_PATH}/examples:${ATB_HOME_PATH}/tests/atbopstest:$LD_LIBRARY_PATH \
    PATH=${ATB_HOME_PATH}/bin:$PATH \
    ASDOPS_HOME_PATH=${ATB_HOME_PATH}
# # NOTE: The one and only non-path env
# ENV ASDOPS_MATMUL_PP_FLAG=1

# NNAL non-path envs
ENV ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ENV ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ENV ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ENV ATB_OPSRUNNER_SETUP_CACHE_ENABLE=1
ENV ATB_OPSRUNNER_KERNEL_CACHE_TYPE=3
ENV ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ENV ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
ENV ATB_OPSRUNNER_KERNEL_CACHE_TILING_SIZE=10240
ENV ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ENV ATB_WORKSPACE_MEM_ALLOC_GLOBAL=0
ENV ATB_COMPARE_TILING_EVERY_KERNEL=0
ENV ATB_HOST_TILING_BUFFER_BLOCK_NUM=128
ENV ATB_DEVICE_TILING_BUFFER_BLOCK_NUM=32
ENV ATB_SHARE_MEMORY_NAME_SUFFIX=""
ENV ATB_LAUNCH_KERNEL_WITH_TILING=1
ENV ATB_MATMUL_SHUFFLE_K_ENABLE=1
ENV ATB_RUNNER_POOL_SIZE=64

ENV ASDOPS_HOME_PATH=${ATB_HOME_PATH}
ENV ASDOPS_MATMUL_PP_FLAG=1
ENV ASDOPS_LOG_LEVEL=ERROR
ENV ASDOPS_LOG_TO_STDOUT=0
ENV ASDOPS_LOG_TO_FILE=1
ENV ASDOPS_LOG_TO_FILE_FLUSH=0
ENV ASDOPS_LOG_TO_BOOST_TYPE=atb
ENV ASDOPS_LOG_PATH=~
ENV ASDOPS_TILING_PARSE_CACHE_DISABLE=0
ENV LCCL_DETERMINISTIC=0

RUN wget -q http://172.17.0.1:3000/Ascend-cann-toolkit_${CANN_VERSION}_linux-${ARCH}.run -P /home/mindieuser/package && \
    wget -q http://172.17.0.1:3000/Ascend-cann-nnal_${CANN_VERSION}_linux-${ARCH}.run -P /home/mindieuser/package && \
    wget -q http://172.17.0.1:3000/Ascend-cann-kernels-${DEVICE}_${CANN_VERSION}_linux-${ARCH}.run -P /home/mindieuser/package && \
    chmod +x /home/mindieuser/package/*.run && \
    /home/mindieuser/package/Ascend-cann-toolkit_*_linux-*.run --install -q && \
    /home/mindieuser/package/Ascend-cann-kernels-*_*_linux-*.run --install -q && \
    /home/mindieuser/package/Ascend-cann-nnal_*_linux-*.run --install -q && \
    rm -rf /home/mindieuser/package/*


################################################## Install PTA ##################################################
FROM cann AS pta

ENV PYTHONPATH=/home/mindieuser/.local/lib/python${PYTHON_MAJOR_VERSION}/site-packages:$PYTHONPATH \
    PATH=/home/mindieuser/.local/bin:$PATH

ARG DEVICE
ARG TORCH_VERSION
ARG ARCH

RUN wget -q http://172.17.0.1:3000/torch_npu-${TORCH_VERSION}*-cp${PYTHON_SHORT_VERSION}-cp${PYTHON_SHORT_VERSION}-manylinux_2_17_${ARCH}.manylinux2014_${ARCH}.whl -P /home/mindieuser/package && \
    wget -q http://172.17.0.1:3000/requirements-${TORCH_VERSION}.txt -P /home/mindieuser/package && \
    pip install -r /home/mindieuser/package/requirements-${TORCH_VERSION}.txt --no-cache-dir && \
    pip install /home/mindieuser/package/torch_npu*.whl && \
    pip cache purge && \
    rm -rf /home/mindieuser/package/*


################################################## Install MindIE ##################################################
FROM pta AS mindie

# mindie-rt
ENV ASCENDIE_HOME=/home/mindieuser/Ascend/mindie/latest/mindie-rt
ENV TUNE_BANK_PATH=${ASCENDIE_HOME}/aoe \
    LD_LIBRARY_PATH=${ASCENDIE_HOME}/lib:$LD_LIBRARY_PATH
ENV ASCEND_CUSTOM_OPP_PATH=${ASCENDIE_HOME}/ops/vendors/customize:$ASCEND_CUSTOM_OPP_PATH
ENV ASCEND_CUSTOM_OPP_PATH=${ASCENDIE_HOME}/ops/vendors/aie_ascendc:$ASCEND_CUSTOM_OPP_PATH

# mindie-torch
ENV MINDIE_TORCH_HOME=/home/mindieuser/Ascend/mindie/latest/mindie-torch
ENV LD_LIBRARY_PATH=${MINDIE_TORCH_HOME}/lib:$LD_LIBRARY_PATH

# mindie-service
ENV MIES_INSTALL_PATH=/home/mindieuser/Ascend/mindie/latest/mindie-service
ENV LD_LIBRARY_PATH=${MIES_INSTALL_PATH}/lib:${MIES_INSTALL_PATH}/lib/grpc:$LD_LIBRARY_PATH \
    PYTHONPATH=${MIES_INSTALL_PATH}/bin:$PYTHONPATH

# mindie-service non-path envs
ENV ATB_OPERATION_EXECUTE_ASYNC=1
ENV TASK_QUEUE_ENABLE=1
ENV HCCL_BUFFSIZE=120
ENV MINDIE_LOG_TO_STDOUT=0
ENV MINDIE_LOG_TO_FILE=1
ENV ASCEND_SLOG_PRINT_TO_STDOUT=0
ENV ASCEND_GLOBAL_LOG_LEVEL=3
ENV ASCEND_GLOBAL_EVENT_ENABLE=0
ENV ATB_LOG_TO_FILE=0
ENV ATB_LOG_TO_FILE_FLUSH=0
ENV ATB_LOG_TO_STDOUT=0
ENV ATB_LOG_LEVEL=ERROR
ENV ASDOPS_LOG_TO_FILE=0
ENV ASDOPS_LOG_TO_STDOUT=0
ENV ASDOPS_LOG_LEVEL=ERROR
ENV OCK_LOG_LEVEL=ERROR
ENV OCK_LOG_TO_STDOUT=0

# mindie-llm
ENV MINDIE_LLM_HOME_PATH=/home/mindieuser/Ascend/mindie/latest/mindie-llm
ENV MINDIE_LLM_PYTHON_LOG_PATH=${MINDIE_LLM_HOME_PATH}/logs/pythonlog.log \
    PYTHONPATH=${MINDIE_LLM_HOME_PATH}:${MINDIE_LLM_HOME_PATH}/lib:$PYTHONPATH \
    LD_LIBRARY_PATH=${MINDIE_LLM_HOME_PATH}/lib:${MINDIE_LLM_HOME_PATH}/lib/grpc:$LD_LIBRARY_PATH

# mindie-llm non-path envs
ENV MINDIE_LLM_PYTHON_LOG_LEVEL=INFO
ENV MINDIE_LLM_PYTHON_LOG_TO_STDOUT=1
ENV MINDIE_LLM_PYTHON_LOG_TO_FILE=0
ENV MINDIE_LLM_LOG_LEVEL=INFO
ENV MINDIE_LLM_LOG_TO_STDOUT=0
ENV MINDIE_LLM_LOG_TO_FILE=1
ENV MINDIE_LLM_CONTINUOUS_BATCHING=1
ENV MINDIE_LLM_RECOMPUTE_THRESHOLD=0.5

# ATB-Models
ENV ATB_SPEED_HOME_PATH=/home/mindieuser/Ascend/atb-models
ENV LD_LIBRARY_PATH=${ATB_SPEED_HOME_PATH}/lib:$LD_LIBRARY_PATH \
    PYTHONPATH=${ATB_SPEED_HOME_PATH}:$PYTHONPATH
ENV PYTORCH_INSTALL_PATH=/home/mindieuser/.local/lib/python${PYTHON_MAJOR_VERSION}/site-packages/torch \
    LD_LIBRARY_PATH=${PYTORCH_INSTALL_PATH}/lib:$LD_LIBRARY_PATH
ENV PYTORCH_NPU_INSTALL_PATH=/home/mindieuser/.local/lib/python${PYTHON_MAJOR_VERSION}/site-packages/torch_npu \
    LD_LIBRARY_PATH=${PYTORCH_NPU_INSTALL_PATH}/lib:$LD_LIBRARY_PATH

# ATB-Models non-path envs
ENV TASK_QUEUE_ENABLE=1
ENV ATB_OPERATION_EXECUTE_ASYNC=1
ENV ATB_CONTEXT_HOSTTILING_RING=1
ENV ATB_CONTEXT_HOSTTILING_SIZE=102400
ENV ATB_WORKSPACE_MEM_ALLOC_GLOBAL=1
ENV ATB_USE_TILING_COPY_STREAM=0
ENV ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ENV ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=16

ARG DEVICE
ARG ARCH
ARG TORCH_VERSION
ARG MINDIE_VERSION

RUN wget -q http://172.17.0.1:3000/Ascend-mindie_${MINDIE_VERSION}_linux-${ARCH}.run -P /home/mindieuser/package && \
    wget -q http://172.17.0.1:3000/Ascend-mindie-atb-models_${MINDIE_VERSION}_linux-${ARCH}_py${PYTHON_SHORT_VERSION}_torch${TORCH_VERSION}-abi0.tar.gz -P /home/mindieuser/package && \
    mkdir -p /home/mindieuser/Ascend/atb-models && \
    tar -xzf /home/mindieuser/package/Ascend-mindie-atb-models*.tar.gz -C /home/mindieuser/Ascend/atb-models && \
    chmod +x /home/mindieuser/package/*.run && \
    /home/mindieuser/package/Ascend-mindie_*_linux-*.run --install -q && \
    chmod u+w $MINDIE_LLM_HOME_PATH && \
    mkdir $MINDIE_LLM_HOME_PATH/logs && \
    chmod 750 $MINDIE_LLM_HOME_PATH/logs && \
    pip cache purge && \
    rm -rf /home/mindieuser/package/*