ARG BASE_VERSION
ARG BASE=ascend-toolkit:$BASE_VERSION
FROM ubuntu:20.04 as buildtemp
COPY . /tmp

FROM $BASE

WORKDIR /tmp

ARG ASCEND_BASE=/usr/local/Ascend

SHELL ["/bin/bash","-c"]

ENV LD_LIBRARY_PATH=/usr/local/python3.9.2/lib: \
    PATH=/usr/local/python3.9.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# HwHiAiUser
RUN groupadd  HwHiAiUser -g 1000 && \
    useradd -d /home/HwHiAiUser -u 1000 -g 1000 -m -s /bin/bash HwHiAiUser

# python包
RUN --mount=type=cache,target=/tmp,from=buildtemp,source=/tmp \
    umask 0022  && \
    mkdir -p /job/code /home/HwHiAiUser/samples/scripts && \
    mkdir -p /home/HwHiAiUser/distributed /home/HwHiAiUser/flops /home/HwHiAiUser/ais /home/HwHiAiUser/hccl && \
    chown HwHiAiUser:HwHiAiUser -R /job /home/HwHiAiUser && \
    pip3 install pip -U && \
    pip3 install -r /tmp/requirements.txt && \
    pip3 install /tmp/mindx_elastic*.whl && \
    rm -rf /root/.cache/pip

# 环境变量
ENV GLOG_v=2
ARG TOOLKIT_PATH=/usr/local/Ascend/ascend-toolkit/latest
ENV TBE_IMPL_PATH=$TOOLKIT_PATH/opp/op_impl/built-in/ai_core/tbe
ENV PYTHONPATH=$TBE_IMPL_PATH:$PYTHONPATH
ENV PATH=$TOOLKIT_PATH/ccec_compiler/bin/:\
/usr/local/Ascend/toolbox/latest/Ascend-DMI/bin:\
/usr/local/mpich-3.2.1/bin:\
$TOOLKIT_PATH/tools/hccl_test/bin:\
$PATH
ENV ASCEND_OPP_PATH=$TOOLKIT_PATH/opp
ENV ASCEND_AICPU_PATH=$TOOLKIT_PATH
ENV LD_LIBRARY_PATH=$TOOLKIT_PATH/lib64:\
/usr/local/Ascend/driver/lib64/:\
/usr/local/Ascend/driver/lib64/common/:\
/usr/local/Ascend/driver/lib64/driver/:\
/usr/local/Ascend/driver/tools/hccn_tool/:\
/usr/local/mpich-3.2.1/lib:\
$TOOLKIT_PATH/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64/:\
/usr/local/Ascend/toolbox/latest/Ascend-DMI/lib64:\
/user/local/dcmi:\
$TOOLKIT_PATH/aarch64-linux/devlib:\
$LD_LIBRARY_PATH

# CANN包
RUN --mount=type=cache,target=/tmp,from=buildtemp,source=/tmp \
    umask 0022  && \
    chmod +x /tmp/*.run && \
    bash /tmp/Ascend-mindx-toolbox*.run --install-path=/usr/local/Ascend/ --install --quiet --install-for-all && \
# TRAIN_FRAMEWORK安装
    pip3 install /tmp/mindspore*.whl && \
    pip3 install $TOOLKIT_PATH/fwkacllib/lib64/te-*.whl && \
    pip3 install $TOOLKIT_PATH/fwkacllib/lib64/hccl-*.whl && \
    pip3 install --upgrade /tmp/torch_npu*.whl && \
    pip3 install --upgrade /tmp/apex-*.whl && \
    pip3 install --upgrade /tmp/torch-*.whl

# hccl_test安裝
RUN umask 0022 && \
    curl -O -k https://www.mpich.org/static/downloads/3.2.1/mpich-3.2.1.tar.gz && \
    tar -zxvf mpich-3.2.1.tar.gz && \
    cd mpich-3.2.1 && \
    ./configure --prefix=/usr/local/mpich-3.2.1 && \
    make && \
    make install && \
    cd $TOOLKIT_PATH/tools/hccl_test && \
    make MPI_HOME=/usr/local/mpich-3.2.1 ASCEND_DIR=$TOOLKIT_PATH/aarch64-linux

# 安装ssh
RUN apt-get update && \
    apt-get --no-install-recommends install openssh-server -y && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config

# gpt3模型数据
RUN --mount=type=cache,target=/tmp,from=buildtemp,source=/tmp \
    umask 0022 && \
    cp -r /tmp/Megatron-LM/ /home/HwHiAiUser/distributed/Megatron-LM && \
    chown -R HwHiAiUser:HwHiAiUser /home/HwHiAiUser/distributed/Megatron-LM && \
    cd /home/HwHiAiUser/distributed/Megatron-LM/megatron_npu && \
    pip3 install -e . && \
    pip3 install -r requirements.txt && \
    pip3 install psutil

# 清理工作
 RUN rm -rf /tmp/*  && \
     rm -rf /root/.cache/pip \

ENV LD_PERLOAD=/lib/aarch64-linux-gnu/libGLdispatch.so.0:$LD_PERLOAD

USER HwHiAiUser

COPY --chown=HwHiAiUser:HwHiAiUser Open_Source_Software_Notice.txt /home/HwHiAiUser/samples/Open_Source_Software_Notice.txt
COPY --chown=HwHiAiUser:HwHiAiUser hccl_run.sh /home/HwHiAiUser/hccl/hccl_run.sh
COPY --chown=HwHiAiUser:HwHiAiUser run_ais.py /home/HwHiAiUser/ais/run_ais.py
COPY --chown=HwHiAiUser:HwHiAiUser flops_test.py /home/HwHiAiUser/flops/flops_test.py
COPY --chown=HwHiAiUser:HwHiAiUser train_huawei_train_mindspore_bert-Ais-Benchmark-Stubs-aarch64-1.0-r2.3 /home/HwHiAiUser/samples/train_huawei_train_mindspore_bert-Ais-Benchmark-Stubs-aarch64-1.0-r2.3
COPY --chown=HwHiAiUser:HwHiAiUser train_huawei_train_mindspore_resnet-Ais-Benchmark-Stubs-aarch64-1.0-r2.3 /home/HwHiAiUser/samples/train_huawei_train_mindspore_resnet-Ais-Benchmark-Stubs-aarch64-1.0-r2.3

WORKDIR /home/HwHiAiUser/