ARG BASE_VERSION
ARG BASE=ascend-toolkit:$BASE_VERSION
FROM ubuntu:20.04 as buildtemp
COPY . /tmp

FROM $BASE

WORKDIR /tmp

ARG ASCEND_BASE=/usr/local/Ascend

SHELL ["/bin/bash","-c"]

ENV LD_LIBRARY_PATH=/usr/local/python3.9.2/lib: \
    PATH=/usr/local/python3.9.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# HwHiAiUser
RUN groupadd  HwHiAiUser -g 1000 && \
    useradd -d /home/HwHiAiUser -u 1000 -g 1000 -m -s /bin/bash HwHiAiUser

# python包
RUN --mount=type=cache,target=/tmp,from=buildtemp,source=/tmp \
    umask 0022  && \
    mkdir -p /job/code /home/HwHiAiUser/samples/scripts && \
    mkdir -p /home/HwHiAiUser/distributed /home/HwHiAiUser/flops /home/HwHiAiUser/ais /home/HwHiAiUser/hccl && \
    chown HwHiAiUser:HwHiAiUser -R /job /home/HwHiAiUser && \
    pip3 install pip -U && \
    pip3 install -r /tmp/requirements.txt && \
    pip3 install /tmp/mindx_elastic*.whl && \
    rm -rf /root/.cache/pip

# 环境变量
ENV GLOG_v=2
ARG TOOLKIT_PATH=/usr/local/Ascend/ascend-toolkit/latest
ENV TBE_IMPL_PATH=$TOOLKIT_PATH/opp/op_impl/built-in/ai_core/tbe
ENV PYTHONPATH=$TBE_IMPL_PATH:$PYTHONPATH
ENV PATH=$TOOLKIT_PATH/ccec_compiler/bin/:/usr/local/Ascend/toolbox/latest/Ascend-DMI/bin:$PATH
ENV ASCEND_OPP_PATH=$TOOLKIT_PATH/opp
ENV ASCEND_AICPU_PATH=$TOOLKIT_PATH
ENV LD_LIBRARY_PATH=$TOOLKIT_PATH/lib64:\
/usr/local/Ascend/driver/lib64/:\
/usr/local/Ascend/driver/lib64/common/:\
/usr/local/Ascend/driver/lib64/driver/:\
/usr/local/Ascend/driver/tools/hccn_tool/:\
$TOOLKIT_PATH/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64/:\
/usr/local/Ascend/toolbox/latest/Ascend-DMI/lib64:\
/user/local/dcmi:\
$LD_LIBRARY_PATH

# CANN包
RUN --mount=type=cache,target=/tmp,from=buildtemp,source=/tmp \
    umask 0022  && \
    bash /tmp/Ascend-cann-kernels-910b_*.run --install-path=/usr/local/Ascend/ --install --quiet --install-for-all && \
    bash /tmp/Ascend-mindx-toolbox*.run --install-path=/usr/local/Ascend/ --install --quiet --install-for-all && \
# TRAIN_FRAMEWORK安装
    pip3 install /tmp/mindspore*.whl && \
    pip3 install $TOOLKIT_PATH/fwkacllib/lib64/te-*.whl && \
    pip3 install $TOOLKIT_PATH/fwkacllib/lib64/hccl-*.whl && \ 

# 清理工作
    rm -rf /tmp/*  && \
    rm -rf /root/.cache/pip

RUN mkdir -p /user/serverid/devindex/config  && \
    chown -R HwHiAiUser:HwHiAiUser /user/serverid/devindex/config && \
    chmod -R o+x /user
USER HwHiAiUser

COPY --chown=HwHiAiUser:HwHiAiUser Open_Source_Software_Notice.txt /home/HwHiAiUser/samples/Open_Source_Software_Notice.txt
COPY --chown=HwHiAiUser:HwHiAiUser Resnet50_Cifar_for_MindSpore /home/HwHiAiUser/samples/Resnet50_Cifar_for_MindSpore
COPY --chown=HwHiAiUser:HwHiAiUser Resnet50_imagenet2012_for_MindSpore /home/HwHiAiUser/samples/Resnet50_imagenet2012_for_MindSpore
COPY --chown=HwHiAiUser:HwHiAiUser vpc_resnet50_imagenet_classification /home/HwHiAiUser/samples/vpc_resnet50_imagenet_classification
COPY --chown=HwHiAiUser:HwHiAiUser test_model.sh /home/HwHiAiUser/samples/scripts/test_model.sh
COPY --chown=HwHiAiUser:HwHiAiUser hccl.json /user/serverid/devindex/config/hccl.json
COPY --chown=HwHiAiUser:HwHiAiUser run_ais.py /home/HwHiAiUser/samples/scripts/run_ais.py
COPY --chown=HwHiAiUser:HwHiAiUser train_huawei_train_mindspore_bert-Ais-Benchmark-Stubs-aarch64-1.0-r2.3 /home/HwHiAiUser/samples/train_huawei_train_mindspore_bert-Ais-Benchmark-Stubs-aarch64-1.0-r2.3
COPY --chown=HwHiAiUser:HwHiAiUser train_huawei_train_mindspore_resnet-Ais-Benchmark-Stubs-aarch64-1.0-r2.3 /home/HwHiAiUser/samples/train_huawei_train_mindspore_resnet-Ais-Benchmark-Stubs-aarch64-1.0-r2.3

WORKDIR /home/HwHiAiUser/