ARG BASE_VERSION
ARG BASE=ascend-toolkit:$BASE_VERSION
FROM ubuntu:20.04 as buildtemp
COPY . /tmp

FROM $BASE

WORKDIR /tmp
SHELL ["/bin/bash","-c"]

# 安装torch
RUN --mount=type=cache,target=/tmp,from=buildtemp,source=/tmp \
    umask 0022 && \
    groupadd  HwHiAiUser -g 1000 && \
    useradd -d /home/HwHiAiUser -u 1000 -g 1000 -m -s /bin/bash HwHiAiUser && \
    pip3 install -U pip && \
    pip3 install -r /tmp/requirements.txt && \
    pip3 install -U /tmp/torch-2.1.0*.whl /tmp/torch_npu-2.1.0*.whl torchvision /tmp/apex-*.whl && \
    rm -rf /root/.cache/pip && \
    rm -rf ./*

USER HwHiAiUser
COPY --chown=HwHiAiUser:HwHiAiUser Open_Source_Software_Notice.txt /home/HwHiAiUser/Open_Source_Software_Notice.txt
WORKDIR /home/HwHiAiUser/